version: "3.8"

services:
  database:
    image: postgres:15
    restart: always
    container_name: database
    ports:
      - "5432:5432" 
    volumes:
      - database-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env.dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    container_name: backend
    restart: unless-stopped
    env_file:
      - .env.dev
    depends_on:
      - database
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - "./backend:/app"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    container_name: frontend
    restart: unless-stopped
    env_file:
      - .env.dev
    ports:
      - "5173:5173"
      - "3000:3000"
    volumes:
      - "./frontend/src:/app/src"
      - "./frontend/public:/app/public"

volumes:
  database-data: